mod door;

use door::Door;
use stylist::yew::styled_component;
use stylist::Style;
use yew::prelude::*;

fn container_styles() -> Style {
    Style::new(format!(
        r#"
            display: flex;
            align-items: center;
            justify-content: center;
            width: 100%;
            height: 100%;
            background-image: url('/assests/images/repeating_background.avif');
        "#
    ))
    .expect("Css string should be correct")
}

fn calendar_styles() -> Style {
    Style::new(format!(
        r#"
            display: flex;
            flex-wrap: wrap;
            justify-content: space-evenly;
            align-items: center;
            width: 1600px;
            height: 900px;
            background-image: url('/assests/images/cat_background.webp');
            box-shadow: 3px 3px 15px grey;
        "#
    ))
    .expect("Css string should be correct")
}

#[styled_component]
pub fn Calendar() -> Html {
    let permutation = [
        // generated by Markus <3
        1, 22, 11, 5, 20, 9, 10, 13, 6, 19, 4, 18, 17, 3, 12, 21, 16, 7, 23, 14, 8, 2, 24, 15,
    ];
    let doors = permutation
        .iter()
        .map(|number| {
            html! {
                <Door number={number} open={false}/>
            }
        })
        .collect::<Html>();

    html! {
        <div class={container_styles()}>
            <div class={calendar_styles()}>
                { doors }
            </div>
        </div>
    }
}
